# Generated by Django 2.2.9 on 2022-04-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blogpost'),
        ('users', '0001_initial'),
    ]

    operations = [
    ]
